user www;
worker_processes auto;
error_log stderr warn;
pid /run/nginx.pid;

events {
    use epoll;
    worker_connections 1024;
    accept_mutex off;
    multi_accept on;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    server_tokens off;
    include mime.types;
    default_type application/octet-stream;

    send_timeout 60s;
    client_header_timeout 60s;
    client_body_timeout 60s;
    client_max_body_size 0;
    client_body_buffer_size 512k;
    client_header_buffer_size 8k;
    large_client_header_buffers 4 64k;

    underscores_in_headers on;
    recursive_error_pages on;

    open_file_cache max=100000 inactive=20s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;

    fastcgi_connect_timeout 5s;
    fastcgi_send_timeout 90s;
    fastcgi_read_timeout 90s;
    fastcgi_buffering off;
    fastcgi_request_buffering off;
    fastcgi_intercept_errors on;

    log_not_found on;
    access_log /dev/stdout combined;
    error_log /dev/stderr crit;

    real_ip_header X-Resty-Client-Ip;
    set_real_ip_from 0.0.0.0/0;
    set_real_ip_from ::/0;
    map "" $client_real_ip {
        default $remote_addr;
    }

    map $http_x_resty_client_port $client_real_port {
        "" $realip_remote_port;
        default $http_x_resty_client_port;
    }

    map $http_x_forwarded_proto $forward_scheme {
        "http" $http_x_forwarded_proto;
        "https" $http_x_forwarded_proto;
        default $scheme;
    }

    map $forward_scheme $forward_ssl {
        "https" "on";
        default "off";
    }

    upstream phpfpm {
        keepalive 128;
        keepalive_requests 1000;

        server unix:/run/php-fpm.sock;
    }

    server {
        listen 80 default_server;
        server_name _;

        absolute_redirect off;

        root /app/www/public;
        index index.php;

        location = /robots.txt {
            default_type text/plain;
            return 200 "User-Agent: *\nDisallow: /";
        }

        location ~* /\. {
            deny all;
        }

        location ~* \.(jpg|jpeg|gif|png|ico|bmp)$ {
            expires 30d;
        }

        location ~* \.(?:css|js)(?:\.map)?$ {
            expires 7d;
        }

        location ~ ^/(fpm-status|fpm-ping)$ {
            allow 127.0.0.1;
            deny all;
            fastcgi_pass phpfpm;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
            fastcgi_param REQUEST_SCHEME $forward_scheme;
            fastcgi_param HTTPS $forward_ssl;
            fastcgi_param REMOTE_ADDR $client_real_ip;
            fastcgi_param REMOTE_PORT $client_real_port;
            fastcgi_param SERVER_NAME $host;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass phpfpm;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param REQUEST_SCHEME $forward_scheme;
            fastcgi_param HTTPS $forward_ssl;
            fastcgi_param REMOTE_ADDR $client_real_ip;
            fastcgi_param REMOTE_PORT $client_real_port;
            fastcgi_param SERVER_NAME $host;
        }

        location / {
            if (!-e $request_filename) {
                rewrite ^(.*)$ /index.php?s=/$1 last;
                break;
            }
        }
    }
}
